INSERT INTO questions (question) values ('What is the capital of Colombia?');
INSERT INTO questions (question) values ('What is the capital of Russia?');
INSERT INTO questions (question) values ('What is the capital of China?');
INSERT INTO questions (question) values ('What is the capital of India?');
INSERT INTO questions (question) values ('What is the capital of Egypt?');
INSERT INTO questions (question) values ('What is the capital of Mexico?');
INSERT INTO questions (question) values ('What is the capital of Poland?');
INSERT INTO questions (question) values ('What is the capital of Iraq?');
INSERT INTO questions (question) values ('What is the capital of Argentina?');
INSERT INTO questions (question) values ('What is the capital of the United States?');
INSERT INTO questions (question) values ('What is the capital of Norway?');
INSERT INTO questions (question) values ('What is the capital of France?');
INSERT INTO questions (question) values ('What is the capital of Cuba?');
INSERT INTO questions (question) values ('What is the capital of Venezuela?');
INSERT INTO questions (question) values ('What is the capital of Taiwan?');
INSERT INTO questions (question) values ('What is the capital of Philipines?');
INSERT INTO questions (question) values ('What is the capital of Israel?');
INSERT INTO questions (question) values ('What is the capital of Libya?');
INSERT INTO questions (question) values ('What is the capital of New Zealand?');
INSERT INTO questions (question) values ('What is the capital of England?');

INSERT INTO answers (answer, question_id) values ('Bogota', 1);
INSERT INTO answers (answer, question_id) values ('Moscow', 2);
INSERT INTO answers (answer, question_id) values ('Beijing', 3);
INSERT INTO answers (answer, question_id) values ('New Delhi', 4);
INSERT INTO answers (answer, question_id) values ('Cairo', 5);
INSERT INTO answers (answer, question_id) values ('Mexico City', 6);
INSERT INTO answers (answer, question_id) values ('Warsaw', 7);
INSERT INTO answers (answer, question_id) values ('Baghdad', 8);
INSERT INTO answers (answer, question_id) values ('Buenos Aires', 9);
INSERT INTO answers (answer, question_id) values ('Washington D.C.', 10);
INSERT INTO answers (answer, question_id) values ('Oslo', 11);
INSERT INTO answers (answer, question_id) values ('Paris', 12);
INSERT INTO answers (answer, question_id) values ('Havana', 13);
INSERT INTO answers (answer, question_id) values ('Caracas', 14);
INSERT INTO answers (answer, question_id) values ('Taipei', 15);
INSERT INTO answers (answer, question_id) values ('Manila', 16);
INSERT INTO answers (answer, question_id) values ('Tel Aviv', 17);
INSERT INTO answers (answer, question_id) values ('Benghazi', 18);
INSERT INTO answers (answer, question_id) values ('Wellington', 19);
INSERT INTO answers (answer, question_id) values ('London', 20);